spring:
  application:
    name: ZuulGateway
server:
  port: 1997
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    
zuul:
  routes:
    user:
      path: /zuulusers/**
      service-id: userservice-eureka-client
      
    note:
      path: /zuulnotes/**
      service-id: noteservice-eureka-client
#ribbon:
#  ConnectTimeout: 10000
#  ReadTimeout: 30000

#hystrix:
#  threadpool:
#    default:
#      coreSize: 1000
#      maximumSize: 10000
#      queueSizeRejectionThreshold: -1
#      maxQueueSize: -1
#  command:
#    default:
#      execution:
#        isolation:
#          strategy: THREAD
#          thread:
#              timeoutInMilliseconds: 41000
#
#
#  host:
#    max-total-connections: 10000
#    max-per-route-connections: 50
    
#    zuul.sensitiveHeader=userId

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000 

ribbon:  
  ReadTimeout: 60000  
  ConnectTimeout: 60000  


  host: 
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000